# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:

    customer_controller:
        class: Vivaster\Customer\Infrastructure\Delivery\API\Controller\CustomerController
        calls:
              - [setContainer, ['@service_container']]

    customer.app.action.view:
        class: Vivaster\Customer\Application\ViewCustomerService
        arguments: ['@customer.repo.array', '@customer.app.action.view.transformer', '@event_dispatcher']

    customer.app.action.update:
        class: Vivaster\Customer\Application\UpdateCustomerService
        arguments: ['@customer.repo.array', '@customer.app.action.update.transformer', '@event_dispatcher']

    event_listener.customer:
        class: Vivaster\Customer\Application\EventListener\SomeEventListener
        tags:
            - {name: kernel.event_listener, event: customer.event.renamed,   method: doSomething1}
            - {name: kernel.event_listener, event: customer.event.relocated, method: doSomething2}

    customer.app.action.view.transformer:
        class: Vivaster\Customer\Application\DataTransformer\CustomerJsonDataTransformer

    customer.app.action.update.transformer:
        class: Vivaster\Customer\Application\DataTransformer\CustomerJsonDataTransformer

    customer.repo.array:
        class: Vivaster\Customer\Infrastructure\Persistence\InMemoryCustomerRepository
