# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    customer_controller:
        class: Vivaster\Customer\Infrastructure\Delivery\API\Controller\CustomerController
